name: my_giggz
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^3.0.2
#  This worked:
#  firebase_core: ^0.5.0
#  firebase_auth: ^0.18.0
#  cloud_firestore: ^0.14.2

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
#  firebase_messaging: ^8.0.0-dev.8
  firebase_messaging: ^7.0.3 #Latest version 2020-12-18

  rflutter_alert: ^1.0.3
  modal_progress_hud: ^0.1.3
  url_launcher: ^5.7.10
  navigation_history_observer: ^1.0.3+1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/michael/
    - images/stars/
    - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
